---
sudo: required
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
env:
  - MOLECULE_IMAGE=centos:6
  - MOLECULE_IMAGE=centos:7
  - MOLECULE_IMAGE=centos:8
services:
  - docker
install:
  - pip install tox-travis
before_script:
  - cd ../
  - mv ansible-role-yarn tmiller02.yarn
  - cd tmiller02.yarn
script:
  - tox
