---

- name: Add the yarn repo
  yum_repository:
    name: yarn
    description: Yarn Repository
    baseurl: "https://dl.yarnpkg.com/rpm/"
    gpgcheck: yes
    gpgkey: "https://dl.yarnpkg.com/rpm/pubkey.gpg"

- name: Install yarn
  yum:
    name: yarn
    enablerepo: yarn
    state: present
