---

- name: Converge
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.nodejs
      nodejs_install_npm_user: root
      npm_config_prefix: /root/.npm-global
      npm_config_unsafe_perm: "true"
    - role: tmiller02.yarn
  post_tasks:
    - name: check that the yarn command is present
      command: yarn
      changed_when: false